### ISSUE TITLE
Cycle Nested Roadmap

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#188]
### [Cycle Nested](https://github.com/cyclejs/cycle-core/milestones/Cycle%20Nested)

- [x] Cycle DOM `auto-scope` branch
- [x] Cycle HTTP Driver `auto-scope` branch
- [x] Cycle DOM isolation against children
- [x] Cycle Core `auto-scope` branch
- [x] isolate
- [x] #184 
- [x] Cycle.run to return `{sources, sinks}`, not array.
- [x] #185 
- [x] Rename "dialogue" to "dataflow component" everywhere.
- [x] #186  in `auto-scope` branch
- [x] Deprecate/remove Custom elements from Cycle DOM in `auto-scope` branch
- [x] Release Cycle Core `newmajorversion-rc1` in `auto-scope` branch
- [x] Update Cycle DOM and Cycle HTTP to use Cycle.run returning `{sources, sinks}` in `auto-scope` branch
- [x] Update all (dev)dependencies, in Core, DOM, HTTP (`auto-scope` branches)
- [x] Release Cycle DOM `newmajorversion-rc1` in `auto-scope` branch
- [x] Release Cycle HTTP `newmajorversion-rc1` in `auto-scope` branch
- [x] Write cycle-example with Cycle Nested techniques, in `auto-scope` branch
- [x] Rewrite TodoMVC with Cycle Nested, in `auto-scope` branch
- [x] Write docs (#187)  in `auto-scope` branch
- [x] Write migration guide
  - From custom elements to nested Cycle apps
  - Removed DOM.get()
  - Renamed mockDOMResponse => mockDOMSource
  - `[sinks, sources]` => `{sinks, sources}`
- [x] Release Cycle Core v6.0.0
- [x] Cycle DOM to devdepend on Cycle Core `6.x.x`
- [x] Release Cycle DOM
- [x] Make cycle-examples depend on non-RC versions
- [x] Release Cycle Nested

**Comment by TylorS** [comment]
Would documentation land under #187 for how drivers could implement their own scoping?

**Comment by staltz** [comment]
Yes, we can't forget that bit.

**Comment by Cmdv** [comment]
Should we write docs before `Use and promote the release candidate to the public`?
So the public can have some idea of what is happening and how they might use it straight away :smile:

**Comment by staltz** [comment]
Perhaps yes...

**Comment by Frikki** [comment]
Can I ask why `let` is being used instead of `const` for variables that aren’t supposed to change?

**Comment by staltz** [comment]
Because at the time I started writing Cycle in ES6, there was no convention/consensus when to use const and when to use let. Nowadays it seems const has been more common than let.

**Comment by Frikki** [comment]
http://www.2ality.com/2015/02/es6-scoping.html

**Comment by Frikki** [comment]
I am transforming the *many* example.

**Comment by staltz** [comment]
I'll do the others.

**Comment by Frikki** [comment]
@staltz Do you need any helping hands, or are you good?

**Comment by staltz** [comment]
Any helping hand is good... we still have some trivial examples in cycle-examples to port over to Cycle Nested. They probably don't need any major migration, just perhaps usage of hyperscript-helpers.

**Comment by Frikki** [comment]
<-- assigned TodoMVC

**Comment by Cmdv** [comment]
I can sort out the porting things over to hyperscript-helpers

**Comment by staltz** [comment]
@Cmdv I think cycle-examples/bmi-naive still needs to be converted to hyperscript-helpers

**Comment by Cmdv** [comment]
@staltz sweet I'll do that then :)

**Comment by Frikki** [comment]
@staltz We might be having an issue with how `isolate` works for the DOM driver.

### Overview

The DOM of isolated dataflow components with identical VTrees is recognized as the same VTree by virtual-dom. If a Vtree is switched between two identical dataflow components, the different scopes are appended to class names on each switch.

### Use Case

Switch VTree on button click.

### Reproduce

```js
// index.js
import { run } from '@cycle/core';
import { makeDOMDriver } from '@cycle/dom';
import { Observable } from 'rx';
import isolate from '@cycle/isolate';

import TabApp from './TabApp';

function main(sources) {
    const tabApp = TabApp(sources);

    return {
        DOM: tabApp.DOM
    };
}

run(main, {
    DOM: makeDOMDriver('#root'),
});
```

```js
// TabApp.js
import { Observable } from 'rx';
import isolate from '@cycle/isolate';
import { h1, button, span } from '@cycle/dom';

const TAB1 = true;
const TAB2 = false;

const log = str => x => {
    console.log(str, x);
    return x;
};

export default function TabApp(sources) {
    const tab1 = isolate(Tab1)(sources);
    const tab2 = isolate(Tab2)(sources);

    const tab$ = Observable
        .merge(
            tab1.switchClicks$.map(_ => TAB2),
            tab2.switchClicks$.map(_ => TAB1),
        )
        .startWith(TAB1)
        .tap(log('tab'));

    const vtree$ = tab$
        .flatMapLatest(tab => tab === TAB1 ? tab1.DOM : tab2.DOM);

    return {
        DOM: vtree$,
    };
}

function Tab1({ DOM }) {
    const switchClicks$ = DOM
        .select('.btn')
        .events('click')
        .tap(log('tab1'));

    const vtree$ = Observable.just(
        span({ className: 'tab1' }, [
            h1(['Tab1']),
            button({
                className: 'btn'
            }, ['Show tab 2']),
        ])
    );

    return {
        DOM: vtree$,
        switchClicks$,
    };
}

function Tab2({ DOM }) {
    const switchClicks$ = DOM
        .select('.btn')
        .events('click')
        .tap(log('tab2'));

    const vtree$ = Observable.just(
        span({ className: 'tab2' }, [
            h1(['Tab2']),
            button({
                className: 'btn'
            }, ['Show tab 1']),
        ])
    );

    return {
        DOM: vtree$,
        switchClicks$
    };
}
```

**Comment by staltz** [comment]
Thanks @Frikki for the detailed report. I need to take some time later to try reproducing this. But right now what I can see is:

> The DOM of isolated dataflow components with identical VTrees is recognized as the same VTree by virtual-dom.

The reproducible test doesn't have identical VTrees for the two tabs. One is `span('.tab2')` the other is `span('.tab1')`.

**Comment by Frikki** [comment]
@staltz True, but that is irrelevant for the unwanted behavior. Btw., it’s present with *@cycle/dom-8.0.0-rc3*; most likely earlier versions, too. I’ll try to put up a live example of this.

**Comment by gyzerok** [comment]
@staltz probably you want to use `key` attribute for isolation, not `className`. I think this is better since `key` is a natural way for VDOM to distinguish between trees.

**Comment by staltz** [comment]
@gyzerok yes I'll keep that in mind

**Comment by staltz** [comment]
@Frikki 
![tab1](https://cloud.githubusercontent.com/assets/90512/11709410/2d3aab6e-9f20-11e5-8b97-c178609e1012.gif)

The code you sent seems to be working fine.

**Comment by Frikki** [comment]
@staltz Yes, it will work, but use the inspector and check the CSS classes on the element. They keep being appended.

**Comment by staltz** [comment]
Ok, found it. Thanks.

**Comment by staltz** [comment]
@Frikki bug fixed and test added. For the record, it was vtree mutation (of the className) that created the bug. I didn't use an immutable solution because it's less performant, but still solved the bug.

**Comment by Frikki** [comment]
@staltz I’m wondering about the last points in the list. Do you feel there’s anything I could help with?

**Comment by staltz** [comment]
@Frikki not much, I am writing the docs (was doing that just yesterday). One thing we need help though is Cycle DOM has some recently-added bugs in the issue list. Those seem important and would be great to be fixed.

**Comment by staltz** [comment]
Done!

**Comment by Cmdv** [comment]
yeahhhh

**Comment by fobos** [comment]
Great!

**Comment by gyzerok** [comment]
Cool! Waiting for a clear example of dynamic lists.

**Comment by Frikki** [comment]
@gyzerok Both *TodoMVC* and *many* are clear examples of dynamic lists.

**Comment by staltz** [comment]
> Cool! Waiting for a clear example of dynamic lists.

There will be a chapter dedicated to that. The reason why it's not in the docs site already is that it wasn't a show-stopper for getting Cycle Nested out, so I postponed it.
